# Generated by Django 4.1 on 2022-11-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='minStaff',
            field=models.IntegerField(default=1),
        ),
    ]
