# Generated by Django 4.1 on 2022-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_day_minstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
