# Generated by Django 4.1 on 2022-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='minDaysOff',
            field=models.IntegerField(default=1, verbose_name='Off days'),
        ),
    ]
