# Generated by Django 4.1 on 2022-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_day_minstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
